<?php

global $_MODULE;
$_MODULE = array();
$_MODULE['<{expeditor}default>AdminExpeditor_6469db4ad821b30a18b6115436976da1'] = 'List of confirmed orders';
$_MODULE['<{expeditor}default>AdminExpeditor_a31b14406b9514d425f953656535ab6f'] = 'Send e-mail to';
$_MODULE['<{expeditor}default>AdminExpeditor_de21dc13e1ea638777fbfad49f88b332'] = 'All orders which have the status';
$_MODULE['<{expeditor}default>AdminExpeditor_37c85a61df6352af7285c307022c4413'] = 'No orders with this status.';
$_MODULE['<{expeditor}default>AdminExpeditor_fd76a4fa666d9f787ccddf12b4d723ce'] = 'Tick this';
$_MODULE['<{expeditor}default>AdminExpeditor_9b2fbcdd66ad2f216873427c8d33965b'] = 'Select a CSV file generated by Expeditor';
$_MODULE['<{expeditor}default>expeditor_b6bfaffe7e877d7de2268f069a2c1635'] = 'Inet Expeditor';
$_MODULE['<{expeditor}default>expeditor_e977fcf4b1bac64bce126a5864db8243'] = 'Manage yours orders between Prestashop and your Inet Expeditor software';
$_MODULE['<{expeditor}default>expeditor_9d766be2c89b5af0010ac0c11dcddae7'] = 'Please copy manually';
$_MODULE['<{expeditor}default>expeditor_d02bbc3cb147c272b0445ac5ca7d1a36'] = 'Order status';
$_MODULE['<{expeditor}default>expeditor_4e99088cd7cf4998e33e9a04911a4e27'] = 'Choose the order status of orders exportable to Expeditor.';
$_MODULE['<{expeditor}default>expeditor_2a12a728b67541a12a38628cf619f92c'] = 'Choose the carrier \"LaPoste\", \"ColiPoste\", or other.';
$_MODULE['<{expeditor}default>expeditor_4304f1533288a127467882b483bec630'] = 'No order status specified';
$_MODULE['<{expeditor}default>expeditor_9b2bef340bf4cc155309585e34e32dc5'] = 'Download format file for inserting orders in the Expeditor software';

?>